### ISSUE TITLE
Bad variable name?

### ISSUE THREAD

**Issue by NickLucido** [acshi/eecs556_mri_pnp#1]
https://github.com/acshi/eecs556_mri_pnp/blob/d9f6e82358f635e2e142ca89dd5efe8ed8b3541b/dncnn.jl#L92

I think a bad variable name is causing float32_to_img to error when called externally. It should just be img, but I don't want to break Acshi's code.

**Comment by acshi** [comment]
Oops! Classic case of forgetting to commit a change I made the last time we talked about this! pushed that commit
